# Generated by Django 3.1.6 on 2021-02-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_hour', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedules',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hospital.schedule'),
        ),
    ]
