# Generated by Django 3.1.6 on 2021-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_hour',
            field=models.CharField(choices=[('10:00am - 11:00am', '10:00am - 11:00am'), ('11:00am - 12:00pm', '11:00am - 12:00pm'), ('2:00pm - 3:00pm', '2:00pm - 3:00pm'), ('3:00pm - 4:00pm', '3:00pm - 4:00pm')], default='10:00am - 11:00am', max_length=20),
        ),
    ]
