# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210224_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_image',
            field=models.ImageField(blank=True, upload_to='departments/'),
        ),
    ]
