# Generated by Django 3.1.6 on 2021-02-17 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210217_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_hour', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.schedule'),
            preserve_default=False,
        ),
    ]
