# Generated by Django 3.1.6 on 2021-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210217_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='app_date',
            field=models.DateTimeField(),
        ),
    ]
