# Generated by Django 3.1.6 on 2021-02-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210217_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedules',
            field=models.ForeignKey(default='schedule', on_delete=django.db.models.deletion.CASCADE, to='hospital.schedule'),
        ),
    ]
